ProMeetProject/ProMeetProject/Models/Employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProMeetProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_Id { get; set; }
        public string Name { get; set; }
        public string email_id { get; set; }
        public double phone_number { get; set; }
        public string Address { get; set; }
        public string password { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string ResetPasswordCode { get; set; }
    }
}

ProMeetProject/ProMeetProject/Models/Extended/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ProMeetProject.Models
{
    [MetadataType(typeof(EmployeeMetadata))]
    public partial class Employee
    {
        public string Confirm_password { get; set; }
    }
    public class EmployeeMetadata
    {
        [Required(ErrorMessage = "Employee id is required")]
        [Display(Name = "Employee id")]
        public int Emp_Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Employee Name is required")]
        [Display(Name = "Employee name")]
        public string Name { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Email id is required")]
        [Display(Name = "Email Id")]
        [DataType(DataType.EmailAddress)]
        public string email_id { get; set; }


        [Required(ErrorMessage = "Phone number is required")]
        [DataType(DataType.PhoneNumber)]
        public double phone_number { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Address is required")]
        public string Address { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "password should contain atleast 6 characters")]
        public string password { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "confirm password is required")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage = "password and confirm password should match")]
        [Display(Name = "Confirm password")]
        public string Confirm_password { get; set; }




    }
}

ProMeetProject/ProMeetProject/Controllers/BookingController.cs
using ProMeetProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ProMeetProject.Controllers
{
    public class BookingController : Controller
    {
        public ActionResult Registration()
        {
            return View();
        }
        //Registration post action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registration([Bind(Exclude = "Is_PaymentDone,ActivationCode")] Booking booking)
        {
            bool Status = false;
            string Message = "";

            //Model is valid or not
            if (ModelState.IsValid)
            {
                //Emp_Id exists or not
                var Emp_id = IsEmp_IdExists(booking.Emp_Id);
                if (!Emp_id)
                {
                    ModelState.AddModelError("EmpId Not exists", "Employee Id does not exists");
                    return View(booking);
                }
                var Emp_Name = IsEmp_NameExists(booking.Emp_Name);
                if (!Emp_Name)
                {
                    ModelState.AddModelError("EmpName Not exists", "Employee Name does not exists");
                    return View(booking);
                }
                var id_exists = IsRoomIdExists(booking.room_id);
                if (!id_exists)
                {
                    ModelState.AddModelError("room id Not exists", "Room ID does not exists");
                    return View(booking);
                }
                var Emp_Email_ID = IsEmp_EmailExists(booking.Emp_Email_Id);
                if (!Emp_Email_ID)
                {
                    ModelState.AddModelError("Emp_Email Not exists", "Employee Mail does not exists");
                    return View(booking);
                }


                booking.Is_PaymentDone = false;

                #region Save to database
                using (FinalDatabaseEntities1 fp = new FinalDatabaseEntities1())
                {
                    booking.Is_PaymentDone = true;
                    fp.Bookings.Add(booking);
                    fp.SaveChanges();
                    SendVerificationLinkEmail(booking.Emp_Email_Id,booking.ActivationCode.ToString());
                    Message="Your Booking request has been sent to the admin.You will receive a mail whether booking is confirmed or not from the admin in a while";
                    Status = true;
                }
                #endregion
            }
            else
            {
                Message = "Invalid request";
            }
            ViewBag.Message = Message;
            ViewBag.Status = Status;
            return View(booking);
        }
       
        public ActionResult VerifyAccount(string id)
        {
            bool Status = false;
            using (FinalDatabaseEntities1 dc = new FinalDatabaseEntities1())
            {
                dc.Configuration.ValidateOnSaveEnabled = false;
                var v = dc.Bookings.Where(a => a.ActivationCode == new Guid(id)).FirstOrDefault();
                if (v != null)
                {
                    v.Is_PaymentDone = true;
                    dc.SaveChanges();
                    Status = true;
                }
                else
                {
                    ViewBag.Message = "Invalid Request";
                }
            }
            ViewBag.Status = Status;

            return View();
        }
        [NonAction]
        public bool IsRoomIdExists(int id)
        {
            using (FinalDatabaseEntities1 fp = new FinalDatabaseEntities1())
            {
                var c = fp.Rooms.Where(a => a.room_id == id).FirstOrDefault();
                return c != null;
            }

        }
        [NonAction]
        public bool IsEmp_IdExists(int id)
        {
            using (FinalDatabaseEntities1 fp = new FinalDatabaseEntities1())
            {
                var c = fp.Employees.Where(a => a.Emp_Id == id).FirstOrDefault();
                return c != null;
            }

        }
        [NonAction]
        public bool IsEmp_NameExists(string name)
        {
            using (FinalDatabaseEntities1 fp = new FinalDatabaseEntities1())
            {
                var c = fp.Employees.Where(a => a.Name == name).FirstOrDefault();
                return c != null;
            }

        }
        [NonAction]
        public bool IsEmp_EmailExists(string email)
        {
            using (FinalDatabaseEntities1 fp = new FinalDatabaseEntities1())
            {
                var c = fp.Employees.Where(a => a.email_id == email).FirstOrDefault();
                return c != null;
            }

        }

        [NonAction]
        public void SendVerificationLinkEmail(string emailID,string activationCode, string emailFor = "VerifyAccount")
        {
            var verifyUrl = "/Booking/" + emailFor + "/" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            MailAddress fromEmail = new MailAddress("keerthisudhamathangi@gmail.com");
            MailAddress toEmail = new MailAddress(emailID);
            var fromEmailPassword = "keerthi34"; // Replace with actual password
            string subject = "Meeting Room Booking Notification";
            string body = "<br/><br/>Your Meeting Room details and your payment has been received." +
                "<br/><br/>Thank you for associating with us.Your Booking request has been sent to the admin.You will receive a mail whether booking is confirmed or not from the admin in a while" ;

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                try
                {
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;
                    smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword);
                    smtp.Send(message);

                }
                catch (Exception)
                {

                }

        }

        public ActionResult Display()//Delete booked rooms for admin
        {
            FinalDatabaseEntities1 db = new FinalDatabaseEntities1();
            return View(db.Bookings.ToList());
        }
        public ActionResult Edit(int? id)
        {
            FinalDatabaseEntities1 db = new FinalDatabaseEntities1();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude = "Booking_Id,Emp_Id,Emp_Name,Emp_Email_Id,room_id,location,DateTime,Duration,Payment_money,Is_PaymentDone,ActivationCode")] Booking booking)
        {
            
            string message = "";
            FinalDatabaseEntities1 db = new FinalDatabaseEntities1();
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                message = "Booking has been confirmed";
            }
            else
            {
               ModelState.AddModelError(" ","Booking details cannot be edited");
            }
            ViewBag.Message = message;
            return View(booking);
        }

        public ActionResult ConfirmBooking(string email)
        {
            string message = "";
            Booking booking = new Booking();
            using(FinalDatabaseEntities1 db=new FinalDatabaseEntities1())
            {
                booking.IsBookingConfirmed = true;
                db.SaveChanges();
                SendBookingConfirmedEmail(booking.Emp_Email_Id);
                message = "The meeting room booking is confirmed";
            }
            ViewBag.Message = message;
            return View(booking);
        }
        public void SendBookingConfirmedEmail(string emailID)
        {
          MailAddress fromEmail = new MailAddress("keerthisudhamathangi@gmail.com");
            MailAddress toEmail = new MailAddress(emailID);
            var fromEmailPassword = "keerthi34"; // Replace with actual password
            string subject = "Meeting Room Booking Notification";
            string body = "<br/><br/>Hi,Your Meeting Room has been successfully booked.Thank you for associating with us";
            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                try
                {
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;
                    smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword);
                    smtp.Send(message);

                }
                catch (Exception)
                {

                }

        }

        public ActionResult Index()//To display booked rooms
        {
            FinalDatabaseEntities1 db = new FinalDatabaseEntities1();
            return View(db.Bookings.ToList());
        }

ProMeetProject/ProMeetProject/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using ProMeetProject.Models;
using System.IO;

namespace ProMeetProject.Controllers
{
    public class RoomController : Controller
    {
        // GET: Room
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Room room)
        {
            bool Status = false;
            string message = "";
            var isexists = IsNameExists(room.Vendor_Name);
            if (!isexists)
            {
                ModelState.AddModelError("Not exists", "Vendor Name does not exists");
                return View(room);
            }
            string fileName = Path.GetFileNameWithoutExtension(room.ImageFile.FileName);
            string extension = Path.GetExtension(room.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            room.Image = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            room.ImageFile.SaveAs(fileName);
            using (FinalDatabaseEntities1 db = new FinalDatabaseEntities1())
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                message = "Room details added successfully!";
                Status = true;
            }
            ViewBag.Status = Status;
            ViewBag.Message = message;
            return View(room);
        }
        [HttpGet]
        public ActionResult Display()
        {
            FinalDatabaseEntities1 db = new FinalDatabaseEntities1();
            return View(db.Rooms.ToList());
        }

        [NonAction]
        public bool IsNameExists(string name)
        {
            using (FinalDatabaseEntities1 fp = new FinalDatabaseEntities1())
            {
                var c = fp.Vendors.Where(a => a.name == name).FirstOrDefault();
                return c != null;
            }

        }


    }
}

ProMeetProject/ProMeetProject/Views/Employee/ForgotPassword.cshtml
@{
    ViewBag.Title = "ForgotPassword";
}

<h2>ForgotPassword</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        <div class="text-success">
            @ViewBag.Message
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Email Id</label>
            @Html.TextBox("EmailId", "", new { @class = "form-control" })
            @Html.ValidationMessage("EmailExist", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-success" />
            </div>
        </div>

    </div>
}

ProMeetProject/ProMeetProject/Views/Employee/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
Welcome @HttpContext.Current.User.Identity.Name

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("Logout", "Employee", FormMethod.Post, new { id = "logoutForm" }))
    {
        <a href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
        <br />
        @Html.ActionLink("Book a room", "Display", "Room")
        <br/>
        @Html.ActionLink("Cancel a room","Index","Booking")
    }

}

ProMeetProject/ProMeetProject/Views/Employee/Login.cshtml
@model ProMeetProject.Models.EmployeeLogin

@{
    ViewBag.Title = "Login";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Employee Login</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.email_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email_id, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.email_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RememberMe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.RememberMe)
                    @Html.ValidationMessageFor(model => model.RememberMe, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Register Now", "Registration", "Employee")
</div>
<div>
    @Html.ActionLink("Forgot Password", "ForgotPassword", "Employee")
</div>


@section Scripts
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

ProMeetProject/ProMeetProject/Views/Employee/Registration.cshtml
@model ProMeetProject.Models.Employee

@{
    ViewBag.Title = "Registration";
}

<h3>Employee Registration</h3>
@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-success">
            <strong>Registration Successful!</strong>@ViewBag.Message
        </div>
    }

}
else
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.Emp_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Emp_Id, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Emp_Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email_id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email_id, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.email_id, "", new { @class = "text-danger" })
                    @Html.ValidationMessage("Email exists", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Confirm_password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Confirm_password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Confirm_password, "", new { @class = "text-danger" })
                </div>
            </div>




            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Register" class="btn btn-default" />
                </div>
            </div>
        </div>
        if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                <strong>Error!</strong>@ViewBag.Message
            </div>
        }
    }
}

<div>
    @Html.ActionLink("Login", "Login")
</div>

@section Scripts
    {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

ProMeetProject/ProMeetProject/Views/Employee/ResetPassword.cshtml
@model ProMeetProject.Models.ResetPasswordModel

@{
    ViewBag.Title = "ResetPassword";
}

<h2>Reset Password</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        <div class="text-danger">
            @ViewBag.Message
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(a => a.ResetCode)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Change Password" class="btn btn-default" />
        </div>
    </div>


}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProMeetProject/ProMeetProject/Views/Employee/VerifyAccount.cshtml
@{
    ViewBag.Title = "VerifyAccount";
}

<h2>VerifyAccount</h2>
@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    <div class="alert alert-success">
        <strong>Success!</strong> Your account has been activated successfully. Click here to @Html.ActionLink("Login", "Login", "Employee")
    </div>
}
else
{
    <div class="alert alert-danger">
        <strong>Error!</strong> @ViewBag.Message
    </div>
}