ProMeetProject/ProMeetProject/Models/Extended/Vendor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProMeetProject.Models
{
    [MetadataType(typeof(VendorMetaData))]
    public partial class Vendor
    {
        public string Confirm_password { get; set; }
    }
    public class VendorMetaData
    {
        [Required(ErrorMessage = "Vendor id is required")]
        [Display(Name = "Vendor Id")]
        public int Vendor_Id { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Vendor Name is required")]
        [Display(Name = "Vendor name")]
        public string name { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Email id is required")]
        [Display(Name = "Email Id")]
        [DataType(DataType.EmailAddress)]
        public string Email_id { get; set; }

        [Required(ErrorMessage = "Phone number is required")]
        [DataType(DataType.PhoneNumber)]
        public double phone { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Address is required")]
        [Display(Name = "Address")]
        public string address { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "password should contain atleast 6 characters")]
        public string password { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "confirm password is required")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage = "password and confirm password should match")]
        [Display(Name = "Confirm password")]
        public string Confirm_password { get; set; }
    }
}

ProMeetProject/ProMeetProject/Models/Vendor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProMeetProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Vendor_Id { get; set; }
        public string name { get; set; }
        public string Email_id { get; set; }
        public double phone { get; set; }
        public string address { get; set; }
        public string password { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string ResetPasswordCode { get; set; }
    }
}

ProMeetProject/ProMeetProject/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using ProMeetProject.Models;
using System.IO;

namespace ProMeetProject.Controllers
{
    public class RoomController : Controller
    {
        // GET: Room
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Room room)
        {
            bool Status = false;
            string message = "";
            var isexists = IsNameExists(room.Vendor_Name);
            if (!isexists)
            {
                ModelState.AddModelError("Not exists", "Vendor Name does not exists");
                return View(room);
            }
            string fileName = Path.GetFileNameWithoutExtension(room.ImageFile.FileName);
            string extension = Path.GetExtension(room.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            room.Image = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            room.ImageFile.SaveAs(fileName);
            using (FinalDatabaseEntities1 db = new FinalDatabaseEntities1())
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                message = "Room details added successfully!";
                Status = true;
            }
            ViewBag.Status = Status;
            ViewBag.Message = message;
            return View(room);
        }
        [HttpGet]
        public ActionResult Display()
        {
            FinalDatabaseEntities1 db = new FinalDatabaseEntities1();
            return View(db.Rooms.ToList());
        }

        [NonAction]
        public bool IsNameExists(string name)
        {
            using (FinalDatabaseEntities1 fp = new FinalDatabaseEntities1())
            {
                var c = fp.Vendors.Where(a => a.name == name).FirstOrDefault();
                return c != null;
            }

        }


    }
}

ProMeetProject/ProMeetProject/Controllers/VendorController.cs
using ProMeetProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ProMeetProject.Controllers
{
    public class VendorController : Controller
    {
        public ActionResult Registration()
        {
            return View();
        }
        //Registration post action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registration([Bind(Exclude = "IsEmailVerified,ActivationCode")]Vendor v)
        {
            bool Status = false;
            string Message = "";

            //Model is valid or not
            if (ModelState.IsValid)
            {
                #region//email already exists or not
                var isexists = IsEmailExists(v.Email_id);
                if (isexists)
                {
                    ModelState.AddModelError("Email exists", "Email already exists");
                    return View(v);
                }
                #endregion
                #region Generate Activation Code
                v.ActivationCode = Guid.NewGuid();
                #endregion

                #region Password hashing
                v.password = Crypto.Hash(v.password);
                v.Confirm_password = Crypto.Hash(v.Confirm_password);
                #endregion
                v.IsEmailVerified = false;

                #region Save to database
                using (FinalDatabaseEntities1 fp = new FinalDatabaseEntities1())
                {
                    fp.Vendors.Add(v);
                    fp.SaveChanges();
                    SendVerificationLinkEmail(v.Email_id, v.ActivationCode.ToString());
                    Message = "Registration successfully done.Account activation link" + " has been sent to your email_id" + v.Email_id;
                    Status = true;
                }
                #endregion
            }
            else
            {
                Message = "Invalid request";
            }
            ViewBag.Message = Message;
            ViewBag.Status = Status;
            return View(v);
        }


        //Verify Account  

        [HttpGet]
        public ActionResult VerifyAccount(string id)
        {
            bool Status = false;
            using (FinalDatabaseEntities1 dc = new FinalDatabaseEntities1())
            {
                dc.Configuration.ValidateOnSaveEnabled = false;
                var v = dc.Vendors.Where(a => a.ActivationCode == new Guid(id)).FirstOrDefault();
                if (v != null)
                {
                    v.IsEmailVerified = true;
                    dc.SaveChanges();
                    Status = true;
                }
                else
                {
                    ViewBag.Message = "Invalid Request";
                }
            }
            ViewBag.Status = Status;
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        //Login post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(VendorLogin login, string ReturnUrl)
        {
            string message = "";
            using (FinalDatabaseEntities1 dc = new FinalDatabaseEntities1())
            {
                var c = dc.Vendors.Where(a => a.Email_id == login.email_id).FirstOrDefault();
                if (c != null)
                {
                    if (string.Compare(Crypto.Hash(login.password), c.password) == 0)
                    {
                        int timeout = login.RememberMe ? 525600 : 20;
                        var ticket = new FormsAuthenticationTicket(login.email_id, login.RememberMe, timeout);
                        string encrypted = FormsAuthentication.Encrypt(ticket);
                        var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encrypted);
                        cookie.Expires = DateTime.Now.AddMinutes(timeout);
                        cookie.HttpOnly = true;
                        Response.Cookies.Add(cookie);
                        return RedirectToAction("Index");
                        /*if (Url.IsLocalUrl(ReturnUrl))
                        {
                            return Redirect(ReturnUrl);
                        }
                        else
                        {
                            return RedirectToAction("Index", "Home");
                        }*/
                    }
                    else
                    {
                        //message = "Invalid credential provided";
                        ModelState.AddModelError("", "The username or password is incorrect");

                    }
                }
                else
                {
                    //message = "Invalid credential provided";
                    ModelState.AddModelError("", "The username or password is incorrect");
                }
            }
            //ViewBag.Message = message;
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }

        //Logout
        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
        [NonAction]
        public bool IsEmailExists(string email_id)
        {
            using (FinalDatabaseEntities1 fp = new FinalDatabaseEntities1())
            {
                var c = fp.Vendors.Where(a => a.Email_id == email_id).FirstOrDefault();
                return c != null;
            }

        }
        [NonAction]
        public void SendVerificationLinkEmail(string emailID, string activationCode, string emailFor = "VerifyAccount")
        {
            var verifyUrl = "/Vendor/" + emailFor + "/" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            MailAddress fromEmail = new MailAddress("keerthisudhamathangi@gmail.com");
            MailAddress toEmail = new MailAddress(emailID);
            var fromEmailPassword = "keerthi34"; // Replace with actual password
            string subject = "";
            string body = "";
            if (emailFor == "VerifyAccount")
            {
                subject = "Your account is successfully created!";

                body = "<br/><br/>We are excited to tell you that your account is" +
                    " successfully created. Please click on the below link to verify your account" +
                    " <br/><br/><a href='" + link + "'>" + link + "</a> ";
            }
            else if (emailFor == "ResetPassword")
            {
                subject = "Reset Password";
                body = "Hi,<br/><br/>We got request for reset your account password.Please Click on the below link to reset your password" +
                    "<br/><br/><a href=" + link + ">" + link + "</a>";


            }
            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                try
                {
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;
                    smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword);
                    smtp.Send(message);

                }
                catch (Exception)
                {

                }

        }

        //Forgot password
        public ActionResult ForgotPassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ForgotPassword(string EmailId)
        {
            string message = "";
            bool status = false;

            using (FinalDatabaseEntities1 dc = new FinalDatabaseEntities1())
            {
                var acc = dc.Vendors.Where(a => a.Email_id == EmailId).FirstOrDefault();
                if (acc != null)
                {
                    string resetCode = Guid.NewGuid().ToString();
                    SendVerificationLinkEmail(acc.Email_id, resetCode, "ResetPassword");
                    message = "Password Reset Link Successfully Sent to Your Mail Id";

                    dc.Configuration.ValidateOnSaveEnabled = false;
                    dc.SaveChanges();

                }
                else
                {
                    ModelState.AddModelError("EmailExist", "Account Not Found with Provided mail Id Please Check the Mail Id and Try again");

                }
                ViewBag.Message = message;
            }
            return View();
        }

        public ActionResult ResetPassword(string id)
        {
            using (FinalDatabaseEntities1 dc = new FinalDatabaseEntities1())
            {
                var user = dc.Vendors.Where(a => a.ResetPasswordCode == id).FirstOrDefault();
                if (user != null)
                {
                    ResetPasswordModel model = new ResetPasswordModel();
                    model.ResetCode = id;
                    return View(model);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResetPassword(ResetPasswordModel model)
        {
            var message = "";
            if (ModelState.IsValid)
            {
                using (FinalDatabaseEntities1 dc = new FinalDatabaseEntities1())
                {

ProMeetProject/ProMeetProject/Views/Vendor/ForgotPassword.cshtml
@{
    ViewBag.Title = "ForgotPassword";
}

<h2>ForgotPassword</h2>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        <div class="text-success">
            @ViewBag.Message
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Email Id</label>
            @Html.TextBox("EmailId", "", new { @class = "form-control" })
            @Html.ValidationMessage("EmailExist", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-success" />
            </div>
        </div>

    </div>
}

ProMeetProject/ProMeetProject/Views/Vendor/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Welcome @HttpContext.Current.User.Identity.Name

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("Logout", "Vendor", FormMethod.Post, new { id = "logoutForm" }))
    {
        <a href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
        <br />
        @Html.ActionLink("Add Room", "Create", "Room")
    }

}

ProMeetProject/ProMeetProject/Views/Vendor/Login.cshtml
@model ProMeetProject.Models.VendorLogin

@{
    ViewBag.Title = "Login";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Vendor Login</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.email_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RememberMe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.RememberMe)
                    @Html.ValidationMessageFor(model => model.RememberMe, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProMeetProject/ProMeetProject/Views/Vendor/Registration.cshtml
@model ProMeetProject.Models.Vendor

@{
    ViewBag.Title = "Registration";
}

<h3>Vendor Registration</h3>
@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-success">
            <strong>Registration Successful!</strong>@ViewBag.Message
        </div>
    }

}

else
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Vendor_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Vendor_Id, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Vendor_Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email_id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email_id, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Email_id, "", new { @class = "text-danger" })
                    @Html.ValidationMessage("Email exists", new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" }, autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>




            <div class="form-group">
                @Html.LabelFor(model => model.Confirm_password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Confirm_password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Confirm_password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Register" class="btn btn-default" />
                </div>
            </div>
        </div>
        if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                <strong>Error!</strong>@ViewBag.Message
            </div>
        }
    }
}

<div>
    @Html.ActionLink("Login", "Login")
</div>

@section Scripts
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

ProMeetProject/ProMeetProject/Views/Vendor/ResetPassword.cshtml
@model ProMeetProject.Models.ResetPasswordModel

@{
    ViewBag.Title = "ResetPassword";
}

<h2>ResetPassword</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reset Password</h4>
        <hr />
        <div class="text-danger">
            @ViewBag.Message
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(a => a.ResetCode)
        </div>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Change Password" class="btn btn-default" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProMeetProject/ProMeetProject/Views/Vendor/VerifyAccount.cshtml
@{
    ViewBag.Title = "VerifyAccount";
}

<h2>VerifyAccount</h2>
@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    <div class="alert alert-success">
        <strong>Success!</strong> Your account has been activated successfully. Click here to @Html.ActionLink("Login", "Login", "Vendor")
    </div>
}
else
{
    <div class="alert alert-danger">
        <strong>Error!</strong> @ViewBag.Message
    </div>
}